import React from 'react'
import Tarif from '../Tarif/Tarif';

export default function TariffList() {

    const teleObjs = [
        {
            id: 1,
            title: "Везде онлайн",
            price: 500,
            ruble: "₽",
            month: "/месяц",
            trafic: 40,
            gb: 'ГБ',
            withoutlimit: "+безлимитные",
            social: [
                "https://msk.tele2.ru/api/media/asset?mediaId=m220005",
                "https://msk.tele2.ru/api/media/asset?mediaId=m220001",
                "https://msk.tele2.ru/api/media/asset?mediaId=m220003",
                "https://msk.tele2.ru/api/media/asset?mediaId=m220006",
                "https://msk.tele2.ru/api/media/asset?mediaId=m220004",
                "https://msk.tele2.ru/api/media/asset?mediaId=m1990041",
                "https://msk.tele2.ru/api/media/asset?mediaId=m1680033",
            ],
            time: 500,
            min: "мин.",
            text: "+ безлимит на Tele2 России",
            messageCount: 50,
            sms: "SMS",
            buyButton: "Купить SIM",
            hit: 'Хит',
            sale: 'продаж',
            hitsale: true,
            socialStatus: true,
            withoutlimitStatus: true,
            messageCountAndSmS: true,
            timeMinStatus: true
        },
        {
            id: 2,
            title: "Мой онлайн",
            price: 400,
            ruble: "₽",
            month: "/месяц",
            trafic: 15,
            gb: 'ГБ',
            withoutlimit: "+безлимитные",
            social: [
                "https://msk.tele2.ru/api/media/asset?mediaId=m220005",
                "https://msk.tele2.ru/api/media/asset?mediaId=m220001",
                "https://msk.tele2.ru/api/media/asset?mediaId=m220003",
                "https://msk.tele2.ru/api/media/asset?mediaId=m220006",
                "https://msk.tele2.ru/api/media/asset?mediaId=m220004",
                "https://msk.tele2.ru/api/media/asset?mediaId=m1990041",
                "https://msk.tele2.ru/api/media/asset?mediaId=m1680033",
            ],
            time: 500,
            min: "мин.",
            text: "+ безлимит на Tele2 России",
            messageCount: 50,
            sms: "SMS",
            buyButton: "Купить SIM",
            hit: 'Хит',
            sale: 'продаж',
            hitsale: false,
            socialStatus: true,
            withoutlimitStatus: true,
            messageCountAndSmS: false,
            timeMinStatus: true
        },
        {
            id: 3,
            title: "Мой онлайн+",
            price: 700,
            ruble: "₽",
            month: "/месяц",
            trafic: 30,
            gb: 'ГБ',
            withoutlimit: "+безлимитные",
            social: [
                "https://msk.tele2.ru/api/media/asset?mediaId=m220005",
                "https://msk.tele2.ru/api/media/asset?mediaId=m220001",
                "https://msk.tele2.ru/api/media/asset?mediaId=m220003",
                "https://msk.tele2.ru/api/media/asset?mediaId=m220006",
                "https://msk.tele2.ru/api/media/asset?mediaId=m220004",
                "https://msk.tele2.ru/api/media/asset?mediaId=m1990041",
                "https://msk.tele2.ru/api/media/asset?mediaId=m1680033",
            ],
            internetOutSide: "Интернет за границей",
            time: 800,
            min: "мин.",
            text: "+ безлимит на Tele2 России",
            messageCount: 50,
            sms: "SMS",
            buyButton: "Купить SIM",
            hit: 'Хит',
            sale: 'продаж',
            hitsale: false,
            socialStatus: true,
            withoutlimitStatus: true,
            messageCountAndSmS: false,
            timeMinStatus: true
        },
        {
            id: 4,
            title: "Мой разговор",
            price: 200,
            ruble: "₽",
            month: "/месяц",
            trafic: 2,
            gb: 'ГБ',
            withoutlimit: "+безлимитные",
            social: [
                "https://msk.tele2.ru/api/media/asset?mediaId=m220005",
                "https://msk.tele2.ru/api/media/asset?mediaId=m220001",
                "https://msk.tele2.ru/api/media/asset?mediaId=m220003",
                "https://msk.tele2.ru/api/media/asset?mediaId=m220006",
                "https://msk.tele2.ru/api/media/asset?mediaId=m220004",
                "https://msk.tele2.ru/api/media/asset?mediaId=m1990041",
                "https://msk.tele2.ru/api/media/asset?mediaId=m1680033",
            ],
            time: 200,
            min: "мин.",
            text: "+ безлимит на Tele2 России",
            messageCount: 50,
            sms: "SMS",
            buyButton: "Купить SIM",
            hit: 'Хит',
            sale: 'продаж',
            hitsale: false,
            socialStatus: false,
            withoutlimitStatus: false,
            messageCountAndSmS: false,
            internetOutSideStatus: true,
            timeMinStatus: true
        },
        {
            id: 5,
            title: "Мой Tele2",
            price: 7,
            ruble: "₽",
            month: "/день",
            trafic: 5,
            gb: 'ГБ',
            withoutlimit: "+безлимитные",
            social: [
                "https://msk.tele2.ru/api/media/asset?mediaId=m220005",
                "https://msk.tele2.ru/api/media/asset?mediaId=m220001",
                "https://msk.tele2.ru/api/media/asset?mediaId=m220003",
                "https://msk.tele2.ru/api/media/asset?mediaId=m220006",
                "https://msk.tele2.ru/api/media/asset?mediaId=m220004",
                "https://msk.tele2.ru/api/media/asset?mediaId=m1990041",
                "https://msk.tele2.ru/api/media/asset?mediaId=m1680033",
            ],
            text: "+ безлимит на Tele2 России",
            messageCount: 50,
            sms: "SMS",
            buyButton: "Купить SIM",
            hit: 'Хит',
            sale: 'продаж',
            hitsale: false,
            socialStatus: false,
            withoutlimitStatus: false,
            messageCountAndSmS: false,
            timeMinStatus: true
        },
        {
            id: 6,
            title: "Безлимит",
            price: 650,
            ruble: "₽",
            month: "/месяц",
            trafic: "Безлимитный интернет",
            withoutlimit: "+безлимитные",
            social: [
                "https://msk.tele2.ru/api/media/asset?mediaId=m220005",
                "https://msk.tele2.ru/api/media/asset?mediaId=m220001",
                "https://msk.tele2.ru/api/media/asset?mediaId=m220003",
                "https://msk.tele2.ru/api/media/asset?mediaId=m220006",
                "https://msk.tele2.ru/api/media/asset?mediaId=m220004",
                "https://msk.tele2.ru/api/media/asset?mediaId=m1990041",
                "https://msk.tele2.ru/api/media/asset?mediaId=m1680033",
            ],
            time: 500,
            min: "мин.",
            text: "+ безлимит на Tele2 России",
            messageCount: 50,
            sms: "SMS",
            buyButton: "Купить SIM",
            hit: 'Хит',
            sale: 'продаж',
            hitsale: false,
            socialStatus: false,
            withoutlimitStatus: false,
            messageCountAndSmS: true,
            timeMinStatus: true

        },
        {
            id: 7,
            title: "Премиум",
            price: 1500,
            ruble: "₽",
            month: "/месяц",
            trafic: 50,
            gb: 'ГБ',
            withoutlimit: "+безлимитные",
            social: [
                "https://msk.tele2.ru/api/media/asset?mediaId=m220005",
                "https://msk.tele2.ru/api/media/asset?mediaId=m220001",
                "https://msk.tele2.ru/api/media/asset?mediaId=m220003",
                "https://msk.tele2.ru/api/media/asset?mediaId=m220006",
                "https://msk.tele2.ru/api/media/asset?mediaId=m220004",
                "https://msk.tele2.ru/api/media/asset?mediaId=m1990041",
                "https://msk.tele2.ru/api/media/asset?mediaId=m1680033",
            ],
            time: 2000,
            min: "мин.",
            text: "+ безлимит на Tele2 России",
            messageCount: 500,
            sms: "SMS",
            buyButton: "Купить SIM",
            hit: 'Хит',
            sale: 'продаж',
            hitsale: false,
            socialStatus: false,
            withoutlimitStatus: false,
            messageCountAndSmS: true,
            timeMinStatus: true
        },
        {
            id: 8,
            title: "Классический",
            titleText: "Без абонентской платы",
            withoutlimit: "+безлимитные",
            social: [
                "https://msk.tele2.ru/api/media/asset?mediaId=m220005",
                "https://msk.tele2.ru/api/media/asset?mediaId=m220001",
                "https://msk.tele2.ru/api/media/asset?mediaId=m220003",
                "https://msk.tele2.ru/api/media/asset?mediaId=m220006",
                "https://msk.tele2.ru/api/media/asset?mediaId=m220004",
                "https://msk.tele2.ru/api/media/asset?mediaId=m1990041",
                "https://msk.tele2.ru/api/media/asset?mediaId=m1680033",
            ],
            time: 2000,
            min: "мин.",
            messageCount: 500,
            sms: "SMS",
            buyButton: "Купить SIM",
            hit: 'Хит',
            sale: 'продаж',
            hitsale: false,
            socialStatus: false,
            withoutlimitStatus: false,
            messageCountAndSmS: false,
            timeMinStatus: false
        },
        {
            id: 9,
            title: "Интернет для устройств",
            titleText: "Без абонентской платы",
            withoutlimit: "+безлимитные",
            social: [
                "https://msk.tele2.ru/api/media/asset?mediaId=m220005",
                "https://msk.tele2.ru/api/media/asset?mediaId=m220001",
                "https://msk.tele2.ru/api/media/asset?mediaId=m220003",
                "https://msk.tele2.ru/api/media/asset?mediaId=m220006",
                "https://msk.tele2.ru/api/media/asset?mediaId=m220004",
                "https://msk.tele2.ru/api/media/asset?mediaId=m1990041",
                "https://msk.tele2.ru/api/media/asset?mediaId=m1680033",
            ],
            time: 500,
            min: "мин.",
            messageCount: 50,
            sms: "SMS",
            buyButton: "Купить SIM",
            hit: 'Хит',
            sale: 'продаж',
            hitsale: false,
            socialStatus: false,
            withoutlimitStatus: false,
            messageCountAndSmS: false,
            internetOutSideStatus: false,
            timeMinStatus: false
        },
        {
            id: 10,
            title: "Интернет для вещей",
            price: 100,
            ruble: "₽",
            month: "/месяц",
            trafic: 300,
            withoutlimit: "+безлимитные",
            mb: 'МБ',
            social: [
                "https://msk.tele2.ru/api/media/asset?mediaId=m220005",
                "https://msk.tele2.ru/api/media/asset?mediaId=m220001",
                "https://msk.tele2.ru/api/media/asset?mediaId=m220003",
                "https://msk.tele2.ru/api/media/asset?mediaId=m220006",
                "https://msk.tele2.ru/api/media/asset?mediaId=m220004",
                "https://msk.tele2.ru/api/media/asset?mediaId=m1990041",
                "https://msk.tele2.ru/api/media/asset?mediaId=m1680033",
            ],
            time: 300,
            min: "мин.",
            messageCount: 100,
            sms: "SMS",
            buyButton: "Купить SIM",
            hit: 'Хит',
            sale: 'продаж',
            hitsale: false,
            socialStatus: false,
            withoutlimitStatus: false,
            messageCountAndSmS: true,
            timeMinStatus: true
        },
    ];
    return (
        <>
            {teleObjs.map(o => <Tarif tele={o}
            />)}
        </>
    )
}
